#!/usr/bin/env bash
# RAG Factory — Scaffold a blueprint into live/
# Usage: ./factory/scaffold.sh <blueprint> <env> <region>
# Example: ./factory/scaffold.sh rag-hybrid dev us-east-1

set -euo pipefail

BLUEPRINT="${1:?Usage: scaffold.sh <blueprint> <env> <region>}"
ENV="${2:?Missing environment (dev|staging|prod)}"
REGION="${3:?Missing region (e.g., us-east-1)}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
BLUEPRINT_DIR="$ROOT/blueprints/$BLUEPRINT"
TARGET_DIR="$ROOT/live/$ENV/${REGION//[-]//}/$BLUEPRINT"

if [[ ! -d "$BLUEPRINT_DIR" ]]; then
    echo "ERROR: Blueprint '$BLUEPRINT' not found at $BLUEPRINT_DIR"
    echo "Available blueprints:"
    ls "$ROOT/blueprints/"
    exit 1
fi

if [[ -d "$TARGET_DIR" ]]; then
    echo "WARNING: $TARGET_DIR already exists. Skipping scaffold."
    exit 0
fi

echo "Scaffolding $BLUEPRINT → $TARGET_DIR"
mkdir -p "$TARGET_DIR"

# Create terragrunt.hcl or backend config
cat > "$TARGET_DIR/backend.tfvars" <<EOF
bucket         = "citadel-tf-state-${ENV}"
key            = "${BLUEPRINT}/${REGION}/terraform.tfstate"
region         = "${REGION}"
dynamodb_table = "citadel-tf-locks"
encrypt        = true
EOF

# Create environment-specific tfvars
cat > "$TARGET_DIR/terraform.tfvars" <<EOF
project     = "citadel-rag"
environment = "${ENV}"
region      = "${REGION}"
EOF

# Symlink or reference the blueprint
cat > "$TARGET_DIR/main.tf" <<EOF
# Generated by scaffold.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Blueprint: ${BLUEPRINT}
# Environment: ${ENV}
# Region: ${REGION}

module "blueprint" {
  source      = "../../../blueprints/${BLUEPRINT}"
  environment = var.environment
  region      = var.region
  project     = var.project
}

variable "project"     { type = string }
variable "environment" { type = string }
variable "region"      { type = string }
EOF

echo "Done. Next steps:"
echo "  cd $TARGET_DIR"
echo "  terraform init -backend-config=backend.tfvars"
echo "  terraform plan -var-file=terraform.tfvars"
